### ISSUE TITLE
How to get models?

### ISSUE THREAD

**Issue by GemsFord** [Artrajz/vits-simple-api#62]
Hi,
Could you please tell me where I can find English models like VCTK?
Also VCTK database has 109 speakers, but yours only has 20.

Thank you.

**Comment by GemsFord** [comment]
@Artrajz Could you please add the support for Gunicorn? So that we can use it in production for parallel processing.

**Comment by Artrajz** [comment]
The VCTK model is from the [original VITS repository](https://github.com/jaywalnut310/vits). You can try to find other English models on Hugging Face, but there are still very few models there.
For the issue of the number of speakers in VCTK, you need to supplement the `speakers` in vctk_base.json to 109 in order to use all of them.
I will add gunicorn support in the Docker deployment.

**Comment by GemsFord** [comment]
I added additional speaker ids and it worked.
Does it support parallel/concurrent requests? If yes, do we need to implement Gunicorn?

Also how can I make sure inferencing is running on GPU and not CPU. Because inferencing gets fast on GPU enabled servers but I don't see GPU utilisation/usage at all.

Thank you for this great contribution.

**Comment by Artrajz** [comment]
Flask itself cannot achieve true parallel/concurrent, so it indeed requires installing Gunicorn for it to support these features.

To run with GPU, you need to install the GPU version of PyTorch and CUDA, then ensure that you can see the following information when starting up:
```
INFO:vits-simple-api:torch:2.0.0+cu117 cuda_available:True
INFO:vits-simple-api:device:cuda device.type:cuda
```
